### ISSUE TITLE
Add offset during reservation

### ISSUE THREAD

**Issue by gelmiro** [dyrkin/luxmed-bot#10]
Problem:
When I create monitoring with auto book I don't want to get reservation if visit is available too fast from reservation moment.For example in 30 minutes because I don't have enough time to visit medical facility.

Solution:
I want to have configuration (maybe global) of restricted time between actual time and visit time. If this will be for example 5 hours, only visit with restriction (actual time + 5h) could be booked automatically.

**Comment by dyrkin** [comment]
Good point!
What do you think would be better, global configuration or one more step in the booking dialogue?
Personally, I prefer add a global setting since the booking dialogue already has many steps. Too many steps annoying.

**Comment by gelmiro** [comment]
@dyrkin Global settings could be annoying If you have few kinds of monitorings. For example if need more time to prepare before visit I want to customize this for particural monitoring. I see that number of steps will increase but maybe this can be configured? User can set global delay (for all monitorings), no delay or ask about delay during setup every monitoring.  More programming but nice flexibility.

**Comment by dyrkin** [comment]
@gelmiro done. Please check when you have a chance

**Comment by gelmiro** [comment]
Everything looks great. Thank you.
