### ISSUE TITLE
no way to use bot after changing password.

### ISSUE THREAD

**Issue by fulara** [dyrkin/luxmed-bot#13]
It seems one is unable to use the bot after changing password.
1) 'remove account' is not implemented.
2) there is no way to clear 'bot state' to forget everything.

My preference would be to add option 2). it can be hidden (not available on menu) but available somehow.

**Comment by dyrkin** [comment]
Hi
Did you try to do any action after changing your password, like executing /reserved command? In case of wrong password the app will ask you to reenter the password.

**Comment by dyrkin** [comment]
Also you can use /login command

**Comment by fulara** [comment]
Thanks for prompt response.
after i used /reserved the app returned an error something like:
'Exception: invalid logon or password'  without letting me to do anything.

when using the `/login` command what I wanted to do is to 'delete account' - thats not implement.
'add account'  did nothing.

I can provide screenshots and gifs if you want.

**Comment by dyrkin** [comment]
/login command lets you reenter your credentials and overrides previous one. Is this a functionality you want? Or do you want to have possibility to remove your data completely?

**Comment by fulara** [comment]
Yes, sorry.  I missed that.
