### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by vonProteus** [dyrkin/luxmed-bot#16]
can you add back automatic building of arm base images
because latest-arm is 1.0.85-arm

**Comment by dyrkin** [comment]
Drone CI for some reason stopped building arm images. This making build badge in the readme always red. I'll try to revert it. Let's see what will happen.

**Comment by dyrkin** [comment]
Check status here: https://cloud.drone.io/dyrkin/luxmed-bot/101

**Comment by dyrkin** [comment]
I've disabled tests for arm builds as they were the reason of failed builds. I think it will be enough to run tests during amd64 build only. 
Use image luxmed-bot:1.0.102-arm or luxmed-bot:latest-arm

**Comment by vonProteus** [comment]
thank you
