### ISSUE TITLE
Luxmed API exception: In order to use this app, please update it to the newest version available in the sto re

### ISSUE THREAD

**Issue by gelmiro** [dyrkin/luxmed-bot#18]
Hi,
there is problem related to sending request to Luxmed API. When I try to make monitoring during visit name selection I got error `Luxmed API exception: In order to use this app, please update it to the newest version available in the store`

Probably API has been changed? Logs Attached

[logs.txt](https://github.com/dyrkin/luxmed-bot/files/5006119/logs.txt)

**Comment by dyrkin** [comment]
Hi,
I noticed it too, but just have no time to take a look. I'll try to fix it in a few days

**Comment by dyrkin** [comment]
It's fixed. Please verify and close the issue

**Comment by gelmiro** [comment]
I saw that there were no changes in API, only identification by headers. That could cause more breaks in the future even if API will be the same. Thx for the fast fix.
