### ISSUE TITLE
Postgres username/password/port configuration in Docker

### ISSUE THREAD

**Issue by pwlgrzs** [dyrkin/luxmed-bot#22]
Hello, would it be possible to allow changes in postgres username/password/port configuration in docker with env variables for eugenezadyra/luxmed-bot containers?

**Comment by dyrkin** [comment]
Hi, I don't have plans to do this, but if you want you can make the change by yourself and I'll be happy to merge your PR. 
To see how to do this you can check `SECURITY_SECRET` and `TELEGRAM_TOKEN` env variables in the `server/src/main/resources/application.yml` file
