### ISSUE TITLE
message: In order to use this app, please update it to the newest version available in the store

### ISSUE THREAD

**Issue by lgeleta** [dyrkin/luxmed-bot#23]
luxmedbookingservice_1  | 2021-10-01 11:40:32 com.lbs.api.http.package$ - Received response:
luxmedbookingservice_1  | Right(HttpResponse({"Errors":[{"ErrorCode":301,"Message":"In order to use this app, please update it to the newest version available in the store.","AdditionalData":{"ShopUrl":"itms-apps://apps.apple.com/pl/app/id552592684","FallbackUrl":"itms-apps://apps.apple.com/pl/app/id552592684","Title":"Update needed"}}]},409,Map(Transfer-Encoding -> Vector(chunked), Server -> Vector(Microsoft-IIS/10.0), Strict-Transport-Security -> Vector(max-age=31536000), Content-Encoding -> Vector(gzip), X-Iinfo -> Vector(5-59915211-59915261 NNYN CT(21 46 0) RT(1633081230773 508) q(0 0 1 0) r(1 1) U6), Content-Type -> Vector(application/json), Date -> Vector(Fri, 01 Oct 2021 09:40:31 GMT), Set-Cookie -> Vector(visid_incap_2269135=LinJ/AiuQtGxncvevsGkcI/XVmEAAAAAQUIPAAAAAADpARt+ACJlH6W/t4DGQUW2; expires=Sat, 01 Oct 2022 01:31:17 GMT; HttpOnly; path=/; Domain=.luxmed.pl; Secure; SameSite=None, incap_ses_729_2269135=1gBsbx/ARh7FD15bDu4dCo/XVmEAAAAAktxGol05vmgyKCDcIljCnw==; path=/; Domain=.luxmed.pl; Secure; SameSite=None), X-CDN -> Vector(Imperva), X-Powered-By -> Vector(ASP.NET), Status -> Vector(HTTP/1.1 409 Conflict))))
luxmedbookingservice_1  | 2021-10-01 11:40:39 c.l.s.service.ApiService - Call to remote api function has completed with result:
luxmedbookingservice_1  | Left(Code: 409, message: In order to use this app, please update it to the newest version available in the store.)
luxmedbookingservice_1  | 2021-10-01 11:40:39 c.l.s.conversation.Book - Can't determine payers for account 4, city 1, clinic None and service 7756
luxmedbookingservice_1  | com.lbs.api.exception.GenericException: Luxmed API exception: In order to use this app, please update it to the newest version available in the store.
luxmedbookingservice_1  | 	at com.lbs.api.http.package$ExtendedHttpRequest.luxmedErrorToApiException(package.scala:73)

**Comment by dyrkin** [comment]
it should be fixed now

**Comment by dyrkin** [comment]
please  updated to the latest version
