### ISSUE TITLE
Bot stopped to work

### ISSUE THREAD

**Issue by xDzmShe** [dyrkin/luxmed-bot#27]
Today the bot stopped to respond to any requests. Do you know what is going on?
![1638469786906](https://user-images.githubusercontent.com/9342328/144481841-3722822c-2f64-4b92-ac72-a4e7f203eecd.jpg)

**Comment by dyrkin** [comment]
Hey, thanks for reporting the issue. I'll check it asap

**Comment by dyrkin** [comment]
I'm using the `bot4s` library to interact with telegram and it seems that it doesn't support user-ids greater than Int.MaxValue. Today we first started receiving messages from a user with an ID greater than this value. this broke the updates parser.
The transition to a new version of the library is very painful, it requires a newer Java and fighting with libraries compatibility.

I'm going to filter out all messages from users with ids greater than Int.MaxValue for now and then will try to update `bot4s` to the latest version.

**Comment by dyrkin** [comment]
It was a bit easier than I thought. Should work now. Please check and close the issue.

**Comment by xDzmShe** [comment]
Everything works as expected now. Thank you for the quick fix.
