### ISSUE TITLE
Bot stopped to work

### ISSUE THREAD

**Issue by Pr3tend3r** [dyrkin/luxmed-bot#32]
Hi,
Yesterday the bot stopped to respond to any requests.

![image](https://user-images.githubusercontent.com/100491855/155858319-032b1351-31df-4245-8c87-18a0bc0d6de3.png)

**Comment by dyrkin** [comment]
Hi. Sorry, I've tried to DDoS russian government sites from the server where the bot is running and it seems this caused a low memory issue there as a result the bot is stopped working. should be fine now

**Comment by Pr3tend3r** [comment]
ok, thx :)
