### ISSUE TITLE
Cannot book a new appointment, monitoring also fails to detect and book appointments.

### ISSUE THREAD

**Issue by Pr3tend3r** [dyrkin/luxmed-bot#33]
Hi,

The bot has been unable to book an appointment for about a week now. It can search for it but when I click book it freez/crashes. 
(I didn't have any appointments booked early)
The same service is already booked. Do you want to update the term? -> I click no and it crashes:

![image](https://user-images.githubusercontent.com/100491855/164062079-962d8fad-e586-4d98-b20f-0c6cf43ff45a.png)

The same service is already booked. Do you want to update the term? -> I click yes - I get this error:

![image](https://user-images.githubusercontent.com/100491855/164062896-6b31a6f7-029a-4772-87fa-b5646579170e.png)

Like I said I didn't have any appointments booked early.

Another problem - probably related:
When I set monitoring, it does not find any free appointments either, despite the fact that after a few days I see them appear on luxmed website.

Could you help with this problem?
Thank you in advance.

**Comment by zoozool** [comment]
hello
i have the same problem, in log i see error:
No HTTP resource was found that matches the request URI 
https://portalpacjenta.luxmed.pl/PatientPortalMobileAPI/api/visits/temporary-reservation'

**Comment by dyrkin** [comment]
Sorry guys, I have no time to fix it right now. Could you fix this?

**Comment by marska** [comment]
@dyrkin what do you use to sniff api?

**Comment by dyrkin** [comment]
@marska [mitm proxy](https://github.com/mitmproxy/mitmproxy)

**Comment by marska** [comment]
I tryied mitm proxy. It looks like the certificate is additionally checked on mobile app. 
After installing the certificate I have a communication error. I can't even log in.

Can someone verify it?

**Comment by dyrkin** [comment]
It works for me. 
Did you install the certificate from http://mitm.it? check if it is not expired. if it is expired, remove the `~/.mitmproxy` directory on your local machine, rerun `mitmweb -p <PORT>`, and download the certificate again from http://mitm.it

**Comment by gelmiro** [comment]
I had also problem with mitm proxy on Android. @dyrkin probably you use ios?

**Comment by dyrkin** [comment]
yep, i'm  on ios

**Comment by kkdrz** [comment]
You may also try to sniff with [Burp](https://portswigger.net/support/configuring-an-ios-device-to-work-with-burp).  
When you [install the certificate](https://portswigger.net/support/installing-burp-suites-ca-certificate-in-an-ios-device) it's important to go to: `Settings > General > About > Certificate Trust Settings`* and enable full trust for PortSwigger cert.
It worked for me.


\* *`Ustawienia -> Ogólne -> To urządzenie -> Ustawienia zaufania certyfikatów`*

**Comment by Pr3tend3r** [comment]
Has anyone managed to solve this problem? There are probably many people who are waiting for an update so that the bot can book appointments. I keep my fingers crossed for success :)

**Comment by dyrkin** [comment]
guys, it has been fixed
