### ISSUE TITLE
Add polish translation

### ISSUE THREAD

**Issue by dyrkin** [dyrkin/luxmed-bot#4]

**Comment by mkmozgawa** [comment]
Any update on that? I'm happy to help if you point me in the direction of the translation files, it would help my non-English speaking family members :)

**Comment by dyrkin** [comment]
Hey. Unfortunately, I have no time to do this so decided to close the issue. But if you want you can copy this file https://github.com/dyrkin/luxmed-bot/blob/master/server/src/main/scala/com/lbs/server/lang/En.scala to https://github.com/dyrkin/luxmed-bot/blob/master/server/src/main/scala/com/lbs/server/lang/Pl.scala, make a translation, give it a unique id by changing the value of `override def id: Int = 2` and add it to the `val Langs: Seq[Lang] = Seq(En, Ua, Pl)` list here: https://github.com/dyrkin/luxmed-bot/blob/2ecb81be07b40394bc4625f76809b74dbac897ac/server/src/main/scala/com/lbs/server/lang/Lang.scala?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L17 and it should work eventually.

**Comment by mkmozgawa** [comment]
Thanks for the pointers! I'll prepare a PR.

**Comment by mkmozgawa** [comment]
Added a PR at #25 👀
