### ISSUE TITLE
Telegram call notification for reservation

### ISSUE THREAD

**Issue by gelmiro** [dyrkin/luxmed-bot#43]
Hi,
I want to request possibility to set call on telegram when visit is booked. Today we have many notifications and sometimes you sam miss that you get appointment at the same day.

Desired behaviour:
* when appointment is booked perform voice call via telegram as "difficult to miss" notification
* option should be possible to set via settings

**Comment by atais** [comment]
i am not sure if its possible, but to me it sounds like it would be easier to remember if you could add a booking to your iCloud/Google callendar? 
Just an export of such event with a notifications set by default would do the job for the bot :-)

**Comment by gelmiro** [comment]
This is not the solution. I want to get incomming call when visit is booked to be sure that I not missed notification when I set 2h offset for example. Sometimes I had to snipe visit for 1 week and you never know when bot will find appointment. If I miss notification (every day dozen of notification from all communicators etc.) also there is high risk that I miss also appointment if will be at the same day. Incomming call is difficult to miss :)

**Comment by dyrkin** [comment]
It seems I have hundred times as few notifications as you. I don't see the need for this feature and would prefer to get as few calls as possible :) But I don't mind if somebody implements this. Do you want to do this?

And just a friendly suggestion to do some notifications hygiene)

**Comment by gelmiro** [comment]
So, I have another pov. I prefer calls instead of notifications. For me notifications are "topics to read when I have time", but luxmed reservation is urgent (as call :) ) I can perform implementation, but in python. If there is some API (HTTP?) to interact with the bot I can prepare my own automation. I don't want to build a bot from scratch because this solution satisfies my needs. Also if you will prepare some endpoints there will be the possibility to prepare an alternative web interface

**Comment by atais** [comment]
honestly, it seems to me like it is your very personal preference for "calls over notifications". 
I'd rather not receive such call neither, because that's what notifications are for.

Maybe you'd want to limit your notifications first :-)? 
Also you should be getting a SMS/Text from LuxMed before the visit, but maybe you did not allow for the mobile communication in your privacy preferences? You can call and check with them.

**Comment by gelmiro** [comment]
The problem is not related to get more notifications from luxmed or SMS. How often do you watch on your phone when you are i.e. working? For me, it is maybe 1 or 2 times for 8 hours. Also, I don't want to reduce notifications and only leave "important" because later I will check all of them, but I don't want to check my phone every 15 minutes when I see some next notifications and check if this one is from the bot if I am waiting few days for reservation which can be in next 2-3 hours from reservation moment. I know that maybe this is a weird way of using a phone but natural for me. I will figure out how to broadcast this message for incoming call when visit is booked.
