### ISSUE TITLE
Bot stopped to respond

### ISSUE THREAD

**Issue by xDzmShe** [dyrkin/luxmed-bot#44]
<img width="575" alt="Screenshot 2022-09-13 at 11 56 48" src="https://user-images.githubusercontent.com/9342328/189872374-e6fe9574-8a38-4677-8dc4-72ff44febfe4.png">

**Comment by dyrkin** [comment]
out of disk space issue. fixed

**Comment by yunasc** [comment]
Hi,

Have to bump this, as bot stopped responding again and I don't have a good place to host my instance.

**Comment by yunasc** [comment]
Please ping me on the same nickname in telegram.
