### ISSUE TITLE
Searching visit with clinic criteria finding no visits

### ISSUE THREAD

**Issue by SirAd** [dyrkin/luxmed-bot#45]
Hi,
I found that I can find any visit if I specified clinic name into search criteria (with "any" working fine). I think API introduced new parameter clinicGroupId and it's causing this issue
`2023-03-15 08:50:29 com.lbs.api.http.package$ - Sending request:
HttpRequest(https://portalpacjenta.luxmed.pl/PatientPortal/NewPortal/terms/index,GET,DefaultConnectFunc,List((cityId,1), (serviceVariantId,7409), (languageId,10), (searchDateFrom,2023-03-15), (searchDateTo,2023-03-19), (searchDatePreset,14), (facilitiesIds,8), (nextSearch,false), (searchByMedicalSpecialist,false)), (...)`

`
2023-03-15 08:50:30 com.lbs.api.http.package$ - Received response:
(...)
{"dateTimeFrom":"2023-03-17T08:30:00","dateTimeTo":"2023-03-17T08:45:00","doctor":{"id":66079,"genderId":0,"academicTitle":"lek.","firstName":"JULIA","lastName":"HAMANKIEWICZ"},"clinicId":44,"clinic":"LX Warszawa - KEN 93","clinicGroupId":8,"clinicGroup":"al. KEN 93","roomId":1471,"serviceId":7409,"scheduleId":10193305,"isImpediment":false,"impedimentText":"","isAdditional":false,"isTelemedicine":false,"isInfectionTreatmentCenter":false,"partOfDay":1}
`
I'm looking for KEN 93 - bot shows me no available visits

**Comment by dyrkin** [comment]
hey. it should be fixed now. please check and reopen the issue if it doesn't work
