### ISSUE TITLE
Luxmed bot is not working anymore

### ISSUE THREAD

**Issue by makc1myc** [dyrkin/luxmed-bot#47]
There is probably an issue, I failed to use luxmed bot, support of bot is finished though? it does not react to any commands anymore:
![tgissue](https://github.com/dyrkin/luxmed-bot/assets/122217697/e01eb3c2-2421-495c-a9db-d5867a301fdb)

**Comment by dyrkin** [comment]
It was out of disk space on my server. Cleaned up a bit. Should be working now

**Comment by Haus681** [comment]
Currently there is the same problem as described above. Can you please check if it`s also server space problem?
