### ISSUE TITLE
Can't select name of a clinic/doctor after some time of use

### ISSUE THREAD

**Issue by chacraborti** [dyrkin/luxmed-bot#48]
I can't select name of a clinic/doctor when looking for ortodont or protetyk (it still works for stomatolog)  despite the fact that I was able to select them previously. When entering the partial name of existing clinic/doctor bot shows nothing.

**Comment by dyrkin** [comment]
could you give the steps to reproduce it

**Comment by dyrkin** [comment]
Closing this as there are no further details provided
