### ISSUE TITLE
409 Error: HTTP/1.1 409 Conflict

### ISSUE THREAD

**Issue by mastakilta** [dyrkin/luxmed-bot#50]
Hi I'm getting
409 Error: HTTP/1.1 409 Conflict
error when trying to log into my account now. The bot used to work fine before (and is great BTW). 
![Screenshot_20231129_000722_Telegram](https://github.com/dyrkin/luxmed-bot/assets/152341408/e07312ff-0243-4a87-91c0-27817c0391d5)

**Comment by dyrkin** [comment]
Hi, I've fixed the error. It just was necessary to update the client version. However, some functionality may appear to be broken. So check it, please, and let me know in case of any issues

**Comment by mastakilta** [comment]
That was quick, many thanks! The bot is awesome!

śr., 29 lis 2023, 01:24 użytkownik Yevhen Zadyra ***@***.***>
napisał:

**Comment by mastakilta** [comment]
Hi, getting the below error now.. :(

500 Error: HTTP/1.1 500 Internal Server Error



śr., 29 lis 2023, 23:54 użytkownik Przemek Klajmon ***@***.***>
napisał:

**Comment by dyrkin** [comment]
Hi. Most likely they've changed the authentication process. Need some time to investigate this. And probably, it won't be today. I'm stopping the bot until the issue gets resolved

**Comment by dyrkin** [comment]
Ok, have fixed the thing. It turned out it was much easier than I thought :)

**Comment by mastakilta** [comment]
Awesome, thanks for the update!

pt., 1 gru 2023, 12:16 użytkownik Yevhen Zadyra ***@***.***>
napisał:

**Comment by dyrkin** [comment]
The idea seems to be good, but in this case, I'd need to store the IDs of the appointments that don't suit a user somewhere in the database and filter them out from each result the bot gets from Luxmed. I'd like not to do this, as the bot doesn't store any state related to Luxmed

**Comment by mastakilta** [comment]
Hmm would you not be able to do this without storing the unsuitable ones?
Just show the option to create monitoring despite available appointments
and for example show notifications each time a new appointment is available?
Also the monitoring is now deleted each time bot finds any appointments,
could it now remain in place until deleted by user? 🤔

pt., 1 gru 2023, 14:08 użytkownik Yevhen Zadyra ***@***.***>
napisał:

**Comment by dyrkin** [comment]
Unfortunately, it is not possible as Luxmed will be returning the same appointments you don't like and the bot will finish the monitoring anyway.

**Comment by mastakilta** [comment]
Understand, but if it didn't finish the monitoring each time it finds
something it could just continue to run and return both the unwanted
appointments as well as new ones, some of which could then be ok :)
Not sure if you see my point but it's just an idea.
Appreciate your work! Have a good weekend.

pt., 1 gru 2023, 15:00 użytkownik Yevhen Zadyra ***@***.***>
napisał:
