### ISSUE TITLE
Not all specialisations are displayed

### ISSUE THREAD

**Issue by Dvdav** [dyrkin/luxmed-bot#60]
It the moment we cannot find Specialisation "Ginekolog endokrynolog". Step to repeat:
1. /boot
2. Kraków
3. "Ginekolog", "Gine", "Endo" or "Ginekolog engokrynolog" values do not show expected specialization.

**Comment by dyrkin** [comment]
I cannot reproduce this. Could you check one more time? And do you see the doctor in your luxmed app?

![image](https://github.com/dyrkin/luxmed-bot/assets/777767/adf258a3-8ad8-44d1-a428-a10e88ea2a93)

**Comment by Dvdav** [comment]
In my case it shows nothing 
![Uploading IMG_5905.png…]()

**Comment by Dvdav** [comment]
Issue can be reproduced in iPhone and Android phones.

**Comment by dyrkin** [comment]
It seems to be a children account, so it doesn't have such options. You need to switch between children and adult accounts using the '/accounts' command.

**Comment by dyrkin** [comment]
Have you tried the luxmed app to see what it shows when you login using this credentials. I'm pretty sure you won't see such options

**Comment by Dvdav** [comment]
Sorry. Issue was related to child account connected. Closing the ticket.
