### ISSUE TITLE
Waiting for changelog lock....

### ISSUE THREAD

**Issue by wilhelmhell** [dyrkin/luxmed-bot#65]
Hi, 
I was having bot succesfully running on Ubuntu 23.10 but then get some DB lock at december and container is stucked at 'waiting for changelock lock' since then. Rebooting, reinstalling docker, changing telegram bot is not helping. Any solution for this?
Best regards.

2024-02-26 10:15:54 scala.App - Starting App using Java 11.0.21 on 97d27f08965f with PID 11 (/app/server.jar started by root in /app)
luxmedbookingservice_1  | 2024-02-26 10:15:54 scala.App - No active profile set, falling back to 1 default profile: "default"
luxmedbookingservice_1  | 2024-02-26 10:15:59 o.s.d.r.c.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
luxmedbookingservice_1  | 2024-02-26 10:15:59 o.s.d.r.c.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 283 ms. Found 0 JPA repository interfaces.
luxmedbookingservice_1  | 2024-02-26 10:16:05 c.z.h.HikariDataSource - HikariPool-1 - Starting...
luxmedbookingservice_1  | 2024-02-26 10:16:06 c.z.h.HikariDataSource - HikariPool-1 - Start completed.
luxmedbookingservice_1  | 2024-02-26 10:16:07 liquibase.database - Set default schema name to public
luxmedbookingservice_1  | 2024-02-26 10:16:08 liquibase.lockservice - Waiting for changelog lock....
luxmedbookingservice_1  | 2024-02-26 10:16:18 liquibase.lockservice - Waiting for changelog lock....
luxmedbookingservice_1  | 2024-02-26 10:16:28 liquibase.lockservice - Waiting for changelog lock....

**Comment by dyrkin** [comment]
Hi. If you don't mind losing your data (you'll have to reenter your Luxmed credentials and lose some history as well as the existing monitorings), you can remove the data volume associated with the Postgres container.
Try this:
```bash
docker-compose down -v #stops and removes all associated containers with volumes. run in the docker-compose.yml file folder.
docker-compose pull #optional. to pull the latest luxmed-bot image
docker-compose up -d #starts everything again
```
Let me know how it went

**Comment by dyrkin** [comment]
@wilhelmhell check my previous comment. Hope it helps.

**Comment by wilhelmhell** [comment]
Hi, 
Removing container data volume with above commands solve the issue. Thanks!
