### ISSUE TITLE
While trying to login java.security.spec.InvalidKeySpecException

### ISSUE THREAD

**Issue by synowiec** [dyrkin/luxmed-bot#66]
As in title; logs below:
`luxmedbookingservice-1  | 2024-03-25 21:36:18 c.l.s.conversation.Login - Step transition failed
luxmedbookingservice-1  | org.jasypt.exceptions.EncryptionInitializationException: java.security.spec.InvalidKeySpecException: Password is not ASCII
luxmedbookingservice-1  |       at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.initialize(StandardPBEByteEncryptor.java:773)
luxmedbookingservice-1  |       at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.initialize(StandardPBEStringEncryptor.java:566)
luxmedbookingservice-1  |       at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.encrypt(StandardPBEStringEncryptor.java:644)
luxmedbookingservice-1  |       at org.jasypt.util.text.StrongTextEncryptor.encrypt(StrongTextEncryptor.java:107)
luxmedbookingservice-1  |       at com.lbs.server.conversation.Login$$anonfun$requestPassword$2.applyOrElse(Login.scala:48)
luxmedbookingservice-1  |       at com.lbs.server.conversation.Login$$anonfun$requestPassword$2.applyOrElse(Login.scala:47)
luxmedbookingservice-1  |       at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
luxmedbookingservice-1  |       at com.lbs.server.conversation.base.Conversation.handle$1(Conversation.scala:41)
luxmedbookingservice-1  |       at com.lbs.server.conversation.base.Conversation.makeStepTransition(Conversation.scala:51)
luxmedbookingservice-1  |       at com.lbs.server.conversation.base.Conversation.makeStepTransition$(Conversation.scala:38)
luxmedbookingservice-1  |       at com.lbs.server.conversation.Login.makeStepTransition(Login.scala:13)
luxmedbookingservice-1  |       at com.lbs.server.conversation.base.Interactional$$anon$1$$anonfun$receive$1.applyOrElse(Interactional.scala:34)
luxmedbookingservice-1  |       at akka.actor.Actor.aroundReceive(Actor.scala:537)
luxmedbookingservice-1  |       at akka.actor.Actor.aroundReceive$(Actor.scala:535)
luxmedbookingservice-1  |       at com.lbs.server.conversation.base.Interactional$$anon$1.aroundReceive(Interactional.scala:28)
luxmedbookingservice-1  |       at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
luxmedbookingservice-1  |       at akka.actor.ActorCell.invoke(ActorCell.scala:548)
luxmedbookingservice-1  |       at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
luxmedbookingservice-1  |       at akka.dispatch.Mailbox.run(Mailbox.scala:231)
luxmedbookingservice-1  |       at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
luxmedbookingservice-1  |       at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
luxmedbookingservice-1  |       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
luxmedbookingservice-1  |       at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
luxmedbookingservice-1  |       at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
luxmedbookingservice-1  |       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
luxmedbookingservice-1  | Caused by: java.security.spec.InvalidKeySpecException: Password is not ASCII
luxmedbookingservice-1  |       at java.base/com.sun.crypto.provider.PBEKey.<init>(Unknown Source)
luxmedbookingservice-1  |       at java.base/com.sun.crypto.provider.PBEKeyFactory.engineGenerateSecret(Unknown Source)
luxmedbookingservice-1  |       at java.base/javax.crypto.SecretKeyFactory.generateSecret(Unknown Source)
luxmedbookingservice-1  |       at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.initialize(StandardPBEByteEncryptor.java:763)
luxmedbookingservice-1  |       ... 24 common frames omitted`

**Comment by dyrkin** [comment]
Hi. It seems you have non-ASCII symbols in your `SECURITY_SECRET`, e.g. Polish. Try to remove them or replace them with ASCII equivalents.

**Comment by synowiec** [comment]
After switching secret works as charm, thank you!
