### ISSUE TITLE
Luxmed bot is not working

### ISSUE THREAD

**Issue by kredz1** [dyrkin/luxmed-bot#69]
Can you please fix the luxmed bot? Monitorings are not working and It's impossible to book anything.

**Comment by dyrkin** [comment]
Why do you think it doesn't work? Any details? I've just managed to book an appointment, but it might that your case is somehow different. I need more details

**Comment by kredz1** [comment]
I book appointment using /book command and then it is not visible in /monitorings
![1](https://github.com/dyrkin/luxmed-bot/assets/167256024/8003012a-8eeb-40c8-8593-e220cd71fda2)
![2](https://github.com/dyrkin/luxmed-bot/assets/167256024/8077c94b-96ae-4442-b2c1-bc797f282661)

**Comment by dyrkin** [comment]
Start the process from the beginning. Then when you choose everything click on the `Szukaj terminów` button. It will show you a list of available terms or the `Create monitoring` button or Polish equivalent. Click on the button

**Comment by kredz1** [comment]
Thank you, it is working now :)
