### ISSUE TITLE
Delay between requests on monitoring

### ISSUE THREAD

**Issue by AdamvAdamiak** [dyrkin/luxmed-bot#74]
Can we have a way to set a delay between requests on monitoring?
When I analyse monitoring I see that request to api to check visits takes 10-15minutes. I would like to change it to 1 minute, 15 minutes window is enough for others to take the visit.

I guess it's this line but I'm not sure, scala is not my language  
https://github.com/dyrkin/luxmed-bot/blob/dd1f91b13c63f63ac4599584307883719e712bd2/server/src/main/scala/com/lbs/server/service/MonitoringService.scala#L47

**Comment by dyrkin** [comment]
Hi. The `delay` var is for delaying monitoring after it's created. The max value is 10 minutes. 
The`period` var is used to specify a delay between monitoring attempts. It consists of 10 minutes base plus a variable value from 0 to up to 5 minutes. This means it can be from 10 to 15 minutes.
I do not recommend changing these values if you don't want your account to be blocked. But you can experiment for sure.
