### ISSUE TITLE
Potentially severe security issue in saved credentials

### ISSUE THREAD

**Issue by mnogiec-cloudinary** [dyrkin/luxmed-bot#76]
Not sure if I'm reading the code correctly, but it seems like credentials are saved as **_plain text_**? 🤔 
IMHO this should really be fixed, or a disclaimer added to README for people who want to try out [the already running bot](https://telegram.me/luxmedbot) but their (potentially) sensitive data isn't hashed or encrypted at all.

**Comment by dyrkin** [comment]
Hi, it's encrypted

https://github.com/dyrkin/luxmed-bot/blob/master/server/src/main/scala/com/lbs/server/conversation/Login.scala#L48

**Comment by mnogiec-cloudinary** [comment]
oh, cool! I missed that, thanks! 🙌
