### ISSUE TITLE
Luxmed API exception: Session expired

### ISSUE THREAD

**Issue by haker146** [dyrkin/luxmed-bot#77]
Recently, when trying to run the boot, the information appears that "Luxmed API exception: Session expired"

**Comment by rvishdev** [comment]
The same for me

**Comment by haker146** [comment]
Today I see that the boot does not respond to queries at all. I don't know if the author has any plan to fix this

**Comment by dyrkin** [comment]
they've renamed one header, so I've updated the app accordingly. please verify

**Comment by haker146** [comment]
It looks like everything is working. Thanks
