### ISSUE TITLE
Nie dziala bot

### ISSUE THREAD

**Issue by jrynkiew** [dyrkin/luxmed-bot#80]
Od wczoraj nie dziala luxmed bot. Telegram nie odpowiada na komendy takie jak /book czy /monitorings

**Comment by AlexSolovev** [comment]
+1 nie działa

**Comment by lakomyt** [comment]
nie jest to problem z outdated libką? w repo jest 5.6.0, a najnowsza to https://github.com/bot4s/telegram/releases/tag/v5.8.3

**Comment by Ukey89** [comment]
Raczej projekt upadł :( mam bota na 2 dockerach i w 1 działa super a w 2gim komendy działają ale nie wyszukuje terminów. Ciekawe czy dev wprowadzi jakieś zmiany

**Comment by dyrkin** [comment]
Hi. Sorry, there is a bug when it books an appointment but doesn't send a notification to a user and doesn't cancel monitoring, so I've stopped it on my server until it's fixed. I have no time to fix it right now. Will try to find some time during the week and let you know when I'm done

**Comment by Calemira** [comment]
Nie działa :((((

**Comment by Ukey89** [comment]
I host bot on my private server. Bot stop working in this moment

2024-11-21 21:01:58 c.l.s.conversation.Pager - Unhandled message received in step 'awaitForData'. Message: [Command(MessageSource(Telegram,5922823973),Message(1070,Some(🦄 Ok! We are going to book the service Pediatra - gabinet dzieci chorych with the doctor chosen AGATA SZLACHCIC in ul. Wołowska 20 clinic of Wrocław city.

Desired dates: 25 Nov 2024 -> 26 Nov 2024

Time: 09:00 -> 20:00

➡ Now choose an action)),Some(find_terms))]. Data: [null]

**Comment by FomfnyN1** [comment]
Również nie działa, nie reaguje na komendy :(

**Comment by Ukey89** [comment]
> Również nie działa, nie reaguje na komendy :(

Masz na swoim serwerze czy korzystasz z ogólnego? Ogólny padł (dev naprawi w wolnej chwili). Jak samemu hostujesz to po drobnych zmianach działa - lub to wina mojego vps

**Comment by dyrkin** [comment]
The issue has been fixed. The bot is back
